# Site settings
<<<<<<< HEAD
description: A blog about lorem ipsum dolor sit amet
baseurl: '' # the subpath of your site, e.g. /blog
url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Lorem Ipsum
user_description: Anon Developer at Lorem Ipsum Dolor
user_title: Anon Developer
email: anon@anon.com
twitter_username: lorem_ipsum
github_username:  lorem_ipsum
gplus_username:  lorem_ipsum
disqus_username: lorem_ipsum

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
=======
title: Your Welcome!!!
email: vgvinay2@gmail.com
description:
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: Vinay Gupta
github_username:  vgvinay2
excerpt_separator: ""
# Build settings
markdown: kramdown
>>>>>>> 7ecf7d1099a553053043a06f027be615ab41dad4
